'use client';

import { useState } from 'react';
import { createPublicClient, createWalletClient, custom, formatEther, http } from 'viem';
import { ANNOUNCER_ABI, monadTestnet, REGISTRY_ABI } from '@/lib/chain';
import { createKeys, matchesAnnouncement, parseMetaAddress, publicKeyFromPrivate } from '@/lib/stealth';

const announcer = process.env.NEXT_PUBLIC_ANNOUNCER_ADDRESS as `0x${string}` | undefined;
const registry = process.env.NEXT_PUBLIC_REGISTRY_ADDRESS as `0x${string}` | undefined;
type Transfer = { address: string; tx: string; block: bigint; balance?: string };

export default function ReceivePage() {
  const [spending, setSpending] = useState(''); const [viewing, setViewing] = useState(''); const [meta, setMeta] = useState('');
  const [items, setItems] = useState<Transfer[]>([]); const [status, setStatus] = useState(''); const [scanning, setScanning] = useState(false); const [registering, setRegistering] = useState(false);
  function generate() { const keys = createKeys(); setSpending(keys.spendingPrivateKey); setViewing(keys.viewingPrivateKey); setMeta(keys.metaAddress); setStatus('Receive keys created locally. Save both private keys before you continue.'); }
  async function register() {
    const keys = parseMetaAddress(meta); if (!keys) return setStatus('Generate receive keys first.'); if (!registry) return setStatus('Wallet address registry is not configured yet.'); if (!window.ethereum) return setStatus('Install or unlock a wallet such as MetaMask.');
    setRegistering(true); try { const wallet = createWalletClient({ chain: monadTestnet, transport: custom(window.ethereum) }); const [account] = await wallet.requestAddresses(); if (await wallet.getChainId() !== monadTestnet.id) throw new Error('Switch your wallet to Monad Testnet.'); setStatus('Confirm registration in your wallet...'); const hash = await wallet.writeContract({ account, address: registry, abi: REGISTRY_ABI, functionName: 'register', args: [keys.spendingPublicKey as `0x${string}`, keys.viewingPublicKey as `0x${string}`] }); await createPublicClient({ chain: monadTestnet, transport: http() }).waitForTransactionReceipt({ hash }); setStatus(`Your wallet can now receive private transfers. Registration: ${hash.slice(0, 10)}...`); } catch (error) { setStatus(error instanceof Error ? error.message : 'Registration was not completed.'); } finally { setRegistering(false); }
  }
  async function scan() {
    if (!announcer) return setStatus('Announcement registry is not configured.'); if (!/^0x[0-9a-fA-F]{64}$/.test(spending) || !/^0x[0-9a-fA-F]{64}$/.test(viewing)) return setStatus('Enter valid 32-byte private spending and viewing keys.');
    setScanning(true); setStatus('Reading Monad announcements...'); try { const client = createPublicClient({ chain: monadTestnet, transport: http() }); const logs = await client.getContractEvents({ address: announcer, abi: ANNOUNCER_ABI, eventName: 'Announcement', fromBlock: 0n, toBlock: 'latest' }); const spendingPublicKey = publicKeyFromPrivate(spending); const matched = await Promise.all(logs.filter(log => log.args.stealthAddress && log.args.ephemeralPubKey && matchesAnnouncement(spendingPublicKey, viewing, log.args.ephemeralPubKey, log.args.stealthAddress)).map(async log => ({ address: log.args.stealthAddress!, tx: log.transactionHash!, block: log.blockNumber!, balance: formatEther(await client.getBalance({ address: log.args.stealthAddress! })) }))); setItems(matched); setStatus(matched.length ? `${matched.length} private transfer${matched.length === 1 ? '' : 's'} discovered.` : 'No matching announcements found yet.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to scan announcements.'); } finally { setScanning(false); }
  }
  return <main className="shell grid-bg px-4 py-5 sm:p-8"><div className="mx-auto max-w-6xl"><Header /><section className="mt-10 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="panel rounded-3xl p-6 sm:p-8"><p className="text-sm font-medium text-violet-300">RECEIVE PRIVATELY</p><h1 className="mt-2 text-3xl font-bold">Enable private receiving</h1><p className="mt-3 text-sm leading-6 text-slate-400">Create private keys, then connect your wallet once so friends can send to your normal wallet address.</p><button className="mt-6 w-full rounded-xl border border-violet-400/30 bg-violet-400/10 px-4 py-3 text-sm font-semibold text-violet-200" onClick={generate}>Generate receive keys</button>{meta && <div className="mt-4 rounded-xl bg-black/20 p-3"><p className="text-xs font-semibold text-slate-400">ADVANCED: GHOSTIFY RECEIVE ADDRESS</p><p className="mt-2 break-all font-mono text-xs leading-5 text-violet-200">{meta}</p><button className="primary mt-4 w-full" disabled={registering} onClick={register}>{registering ? 'Registering...' : 'Enable receiving for my wallet'}</button></div>}<label className="mb-2 mt-6 block text-sm font-medium text-slate-300">Private spending key</label><input className="field font-mono text-sm" type="password" placeholder="0x..." value={spending} onChange={e => setSpending(e.target.value)} /><label className="mb-2 mt-4 block text-sm font-medium text-slate-300">Private viewing key</label><input className="field font-mono text-sm" type="password" placeholder="0x..." value={viewing} onChange={e => setViewing(e.target.value)} /><button className="primary mt-6 w-full" disabled={scanning} onClick={scan}>{scanning ? 'Scanning Monad...' : 'Scan Monad Testnet'}</button>{status && <p role="status" className="mt-4 text-sm leading-6 text-slate-300">{status}</p>}</div><div className="panel rounded-3xl p-6 sm:p-8"><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-violet-300">INCOMING</p><h2 className="mt-2 text-2xl font-bold">Stealth transfers</h2></div><span className="rounded-full bg-white/8 px-3 py-1 text-sm text-slate-300">{items.length} found</span></div>{items.length === 0 ? <div className="mt-10 rounded-2xl border border-dashed border-white/15 p-10 text-center"><p className="font-medium">No transfers displayed</p><p className="mt-2 text-sm text-slate-500">Generate or enter your keys, then scan the announcement registry.</p></div> : <div className="mt-7 space-y-3">{items.map(item => <a key={item.tx} className="block rounded-2xl border border-white/10 bg-white/5 p-4" target="_blank" href={`https://testnet.monadvision.com/tx/${item.tx}`}><div className="flex items-center justify-between gap-3"><div><p className="font-semibold text-emerald-300">+ {item.balance} MON</p><p className="mt-1 font-mono text-xs text-slate-500">{item.address}</p></div><span className="text-xs text-slate-400">Block {item.block.toString()}</span></div></a>)}</div>}</div></section></div></main>;
}
function WalletConnectButton() {
  const [address, setAddress] = useState('');
  async function connect() {
    if (!window.ethereum) return alert('Install or unlock a wallet such as MetaMask.');
    try {
      const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' }) as string[];
      if (accounts[0]) setAddress(accounts[0]);
    } catch { /* user dismissed wallet connection */ }
  }
  return <button className="rounded-lg border border-violet-400/30 bg-violet-400/10 px-3 py-2 text-sm font-semibold text-violet-200" onClick={connect}>{address ? `${address.slice(0, 6)}...${address.slice(-4)}` : 'Connect wallet'}</button>;
}
function Header() { return <header className="flex items-center justify-between"><a href="/" className="flex items-center gap-3 text-xl font-bold tracking-tight"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-violet-500 to-fuchsia-500 text-lg">G</span>Ghostify</a><nav className="flex items-center gap-3"><WalletConnectButton /><a className="navlink" href="/">Send</a><a className="rounded-lg bg-white/8 px-3 py-2 text-sm font-medium text-white" href="/receive">Receive</a></nav></header>; }
