'use client';

import { useEffect, useState } from 'react';
import { createPublicClient, createWalletClient, custom, http, parseEther } from 'viem';
import { monadTestnet, SHIELDED_POOL_ABI } from '@/lib/chain';
import { createShieldedNote, loadNotes, saveNotes, type ShieldedNote } from '@/lib/shielded';

const pool = process.env.NEXT_PUBLIC_SHIELDED_POOL_ADDRESS as `0x${string}` | undefined;
const wasmUrl = process.env.NEXT_PUBLIC_ZK_WASM_URL;
const zkeyUrl = process.env.NEXT_PUBLIC_ZK_ZKEY_URL;
const client = createPublicClient({ chain: monadTestnet, transport: http() });

export default function ShieldedPoolPage() {
  const [wallet, setWallet] = useState(''); const [notes, setNotes] = useState<ShieldedNote[]>([]); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => setNotes(loadNotes()), []);
  async function connect() { if (!window.ethereum) return setStatus('Install or unlock a wallet such as MetaMask.'); try { const wc = createWalletClient({ chain: monadTestnet, transport: custom(window.ethereum) }); const [account] = await wc.requestAddresses(); if (await wc.getChainId() !== monadTestnet.id) throw new Error('Switch to Monad Testnet (chain 10143).'); setWallet(account); setStatus('Wallet connected.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Connection was not completed.'); } }
  async function deposit() {
    if (!pool) return setStatus('Shielded pool is not deployed/configured yet.'); if (!wallet) return setStatus('Connect your wallet first.');
    setBusy(true); try { setStatus('Creating a private note locally...'); const note = await createShieldedNote(); const wc = createWalletClient({ chain: monadTestnet, transport: custom(window.ethereum!) }); setStatus('Confirm the 1 MON deposit in your wallet...'); const hash = await wc.writeContract({ account: wallet as `0x${string}`, address: pool, abi: SHIELDED_POOL_ABI, functionName: 'deposit', args: [note.commitment], value: parseEther('1') }); await client.waitForTransactionReceipt({ hash }); const next = [...notes, note]; setNotes(next); saveNotes(next); setStatus(`Deposit confirmed. Your shielded note is stored only in this browser. Transaction: ${hash.slice(0, 10)}...`); } catch (error) { setStatus(error instanceof Error ? error.message : 'Deposit was not completed.'); } finally { setBusy(false); }
  }
  function clearNotes() { localStorage.removeItem('ghostify-shielded-notes'); setNotes([]); setStatus('Local notes cleared. This cannot recover funds.'); }
  const artifactsReady = Boolean(wasmUrl && zkeyUrl);
  return <main className="shell grid-bg px-4 py-5 sm:p-8"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between"><a href="/" className="flex items-center gap-3 text-xl font-bold"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-violet-500 to-fuchsia-500">G</span>Ghostify</a><div className="flex items-center gap-3"><a className="navlink" href="/receive">Legacy scanner</a><button className="rounded-lg border border-violet-400/30 bg-violet-400/10 px-3 py-2 text-sm font-semibold text-violet-200" onClick={connect}>{wallet ? `${wallet.slice(0, 6)}...${wallet.slice(-4)}` : 'Connect wallet'}</button></div></header>
  <section className="mt-10 grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><div className="panel rounded-3xl p-6 sm:p-9"><p className="text-sm font-medium text-violet-300">SHIELDED POOL V1</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Private 1 MON notes</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">Deposit one fixed denomination, then privately transfer a note inside the pool. Your note secrets remain in this browser.</p><div className="mt-8 rounded-2xl border border-white/10 bg-black/20 p-5"><div className="flex items-center justify-between"><div><p className="font-semibold">Deposit 1 MON</p><p className="mt-1 text-sm text-slate-500">Creates a private commitment in the shielded pool.</p></div><span className="rounded-full bg-violet-400/10 px-3 py-1 text-sm font-semibold text-violet-200">Fixed 1 MON</span></div><button className="primary mt-5 w-full" disabled={busy || !pool || !wallet} onClick={deposit}>{busy ? 'Creating private note...' : 'Deposit 1 MON'}</button>{!pool && <p className="mt-3 text-xs text-amber-300">Pool address not configured. Deploy the testnet stack first.</p>}</div><div className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-5"><div className="flex items-center justify-between"><div><p className="font-semibold">Private send</p><p className="mt-1 text-sm text-slate-500">Proof generation and relayer submission.</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${artifactsReady ? 'bg-emerald-400/10 text-emerald-300' : 'bg-white/10 text-slate-400'}`}>{artifactsReady ? 'Artifacts ready' : 'Awaiting ZK artifacts'}</span></div><button className="mt-5 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-slate-400" disabled>Private send unlocks after CI artifacts are hosted</button></div>{status && <p role="status" className="mt-5 rounded-xl border border-white/10 bg-white/5 p-3 text-sm leading-6 text-slate-300">{status}</p>}</div>
  <aside className="panel rounded-3xl p-6 sm:p-9"><p className="text-sm font-medium text-violet-300">LOCAL NOTES</p><div className="mt-2 flex items-end justify-between"><h2 className="text-2xl font-bold">{notes.length} note{notes.length === 1 ? '' : 's'}</h2>{notes.length > 0 && <button className="text-xs text-rose-300" onClick={clearNotes}>Clear local notes</button>}</div>{notes.length === 0 ? <div className="mt-8 rounded-2xl border border-dashed border-white/15 p-8 text-center text-sm text-slate-500">No local notes. Deposit 1 MON after the pool is configured.</div> : <div className="mt-6 space-y-3">{notes.map(note => <div key={`${note.secret}-${note.nullifier}`} className="rounded-2xl border border-emerald-400/15 bg-emerald-400/5 p-4"><p className="font-semibold text-emerald-300">1 shielded MON</p><p className="mt-2 break-all font-mono text-xs leading-5 text-slate-400">Commitment: {note.commitment}</p><p className="mt-2 text-xs text-amber-200">Back up this browser profile before clearing data. These notes are required to spend.</p></div>)}</div>}<div className="mt-8 rounded-2xl border border-violet-400/15 bg-violet-400/5 p-4 text-sm leading-6 text-violet-200">Testnet only. Deposits are public; privacy begins when a note is privately transferred within the pool. Do not use real funds.</div></aside></section></div></main>;
}
